#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[279] =
    {   0,
        0,    0,    0,    0,    0,    0,   91,   90,    7,    6,
       90,   22,   90,   35,   90,   38,   39,   33,   31,   30,
       32,   88,   34,   12,   11,   88,   26,   28,   27,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   36,   37,
       29,    5,    3,    5,    4,    6,   23,    0,    9,    0,
        0,   29,   15,    1,   87,   16,   12,    0,    0,   12,
       12,    0,   11,   11,   11,   24,   28,   25,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   57,   89,   89,
       89,   89,   89,   89,   66,   89,    0,   89,   89,   89,

       89,   89,   89,   89,   21,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   62,   89,    2,
       13,    0,    0,    0,   15,   15,    0,   16,   16,    0,
       14,   12,   12,   12,    0,   10,   11,   11,   11,   89,
       20,   89,   89,   89,   89,   89,   75,   53,   89,   89,
       89,   61,   89,   89,   89,   89,   59,   85,   51,   50,
       89,   22,   89,   89,   89,   89,   89,   89,    8,   89,
       89,   74,   89,   89,   49,   89,   76,   89,   89,   89,
        0,    0,    0,   15,    0,   16,   14,   14,   12,    0,
        0,   10,    0,   10,   11,   78,   77,   79,   89,   84,

       89,   81,   40,    0,   89,   63,   65,   89,   48,   89,
       64,   89,   89,   52,   89,   42,   89,    8,    8,    8,
        8,   54,   41,   80,   73,   60,   45,   82,   67,   89,
       89,    0,    0,    0,    0,   10,   10,    0,   17,   10,
       46,   89,    0,    0,   83,   69,   86,   89,   68,   89,
       89,   89,   89,   58,    0,   18,    0,   19,   17,   17,
       10,   70,   56,   55,   89,   72,   47,   89,   44,   18,
       18,   19,   19,   89,   89,   71,   43,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    9,   10,    9,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   24,   25,
       26,   27,   28,    9,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   38,
       53,   54,   55,   56,   38,    9,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   38,   38,   66,   67,   68,
       69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
       79,   38,    9,    9,    9,    9,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[80] =
    {   0,
        1,    2,    3,    2,    1,    4,    4,    5,    4,    4,
        6,    4,    4,    4,    4,    4,    4,    7,    4,    8,
        8,    8,    9,    4,    4,    4,    4,    5,    8,    8,
        9,    9,    9,    8,   10,   10,   10,   10,   10,   10,
       11,   10,   10,   10,   11,   10,   11,   10,   11,   10,
       11,   10,    4,    5,    4,    4,    8,    8,    9,    9,
        9,    8,   10,   10,   10,   10,   10,   11,   10,   10,
       10,   11,   10,   11,   10,   11,   10,   11,   10
    } ;

static yyconst flex_int16_t yy_base[289] =
    {   0,
        0,    0,   77,   78,  325,  300,  274,  853,  853,  853,
      262,  237,  237,  853,  188,  853,  853,  220,  853,  853,
      853,   62,   74,   76,   83,  853,   60,  206,  164,   79,
       58,   79,   65,   94,  122,   72,    0,   77,  117,  128,
      135,   74,   84,  140,  179,  145,  173,   59,  853,  853,
      853,  853,  853,  161,  853,  853,  853,  171,  853,   89,
      178,  853,  185,  853,  853,  239,  246,  215,  260,  245,
       97,  148,  269,  247,  116,  853,  853,  853,    0,  134,
      157,  155,  184,  186,  184,  225,  155,    0,  179,  256,
      186,  185,  254,  252,    0,  263,   59,  257,  279,  258,

      277,  268,  277,  285,    0,  290,  288,  307,  278,  293,
      300,  303,  307,  310,  312,  313,  324,  324,  323,  853,
      853,  351,    0,  372,  853,  853,  381,  853,  853,  386,
      390,  315,  853,  325,    0,  379,  351,  853,  375,  369,
        0,  375,  376,  373,  381,  367,  387,    0,  392,  428,
      379,    0,  393,  393,  388,  395,    0,   87,    0,    0,
      391,    0,  408,  409,  408,  423,  408,  410,  484,  438,
      429,  440,  432,  437,    0,  482,  478,  475,  472,  479,
      504,  548,  449,  526,  499,  533,  853,  853,  853,  480,
      487,  525,  512,  497,  853,    0,    0,    0,  515,    0,

      529,    0,    0,  553,  529,    0,    0,  529,    0,   70,
        0,  542,  540,    0,  551,    0,  565,  613,  619,  168,
      624,    0,  584,    0,    0,    0,    0,    0,    0,  602,
      612,  121,    0,  638,  647,  599,  853,  661,  665,  624,
        0,  633,  633,  632,    0,    0,    0,  631,    0,  649,
      639,  658,  655,    0,  685,  689,  712,  718,  853,  853,
      853,    0,  853,  853,  659,    0,    0,  665,    0,  853,
      853,  853,  853,  652,  666,    0,    0,  853,  784,  792,
      803,  807,  814,  819,  821,  823,  831,  841
    } ;

static yyconst flex_int16_t yy_def[289] =
    {   0,
      278,    1,  279,  279,  279,  279,  278,  278,  278,  278,
      278,  278,  280,  278,  281,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  280,  278,  281,
      283,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  284,  278,  278,  278,  278,  278,  278,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  281,  282,  282,  282,

      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  278,
      278,  281,  285,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  286,  284,  278,  278,  278,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  287,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      281,  281,  278,  278,  278,  278,  278,  278,  278,  286,
      286,  278,  278,  278,  278,  282,  282,  282,  282,  282,

      282,  282,  282,  278,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  288,  288,  288,
      287,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  281,  182,  278,  278,  278,  278,  278,  278,  278,
      282,  282,  278,  278,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  278,  278,  278,  278,  278,  278,
      278,  282,  278,  278,  282,  282,  282,  282,  282,  278,
      278,  278,  278,  282,  282,  282,  282,    0,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278
    } ;

static yyconst flex_int16_t yy_nxt[933] =
    {   0,
        8,    9,   10,    8,   11,    9,   12,   13,    8,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   25,   25,   26,   27,   28,   29,    8,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   37,   39,   40,
       41,   42,   43,   37,   44,   45,   46,   47,   37,   48,
       37,   37,   49,    8,   50,   51,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       37,   44,   45,   46,   47,   37,   48,   37,   37,   53,
       53,   63,   63,   63,   63,   76,   57,   64,   84,  247,
       54,   54,   65,   66,  119,   67,   67,   67,   68,  121,

       66,   87,   73,   73,   73,   73,   88,  210,   69,   80,
       95,   85,   61,   94,   70,   69,   84,   96,  105,   81,
       86,   74,  119,   71,   82,   83,   72,   97,  106,   87,
       75,  121,   89,   88,   90,  134,   69,   80,   95,   85,
       94,   70,   61,   69,   96,  105,   81,   86,   74,   98,
       71,   82,   83,   72,  139,  106,  100,   75,   99,   89,
       91,   90,  134,   92,  101,  135,   93,  102,  107,  278,
      278,  278,  108,  116,   61,  140,  103,   98,   59,  120,
      117,  139,  104,   97,  100,   99,  118,   91,  141,   78,
       92,  142,  101,   93,  148,  102,  107,  122,  122,  122,

      108,  116,  140,  103,   63,   63,   63,   63,  117,  104,
      109,  110,  143,  118,  144,  111,  141,  124,  125,  142,
      145,  148,  112,  126,  149,  113,  114,  151,  123,  152,
      115,   77,   66,   62,   68,   68,   68,   68,  109,  110,
      143,   61,  144,  111,   59,  124,  125,   69,  145,  112,
      126,  149,  113,  114,  151,  123,  152,  115,   63,   63,
       63,   63,   57,   66,   56,   67,   67,   67,   68,  146,
      147,  127,  128,  278,  130,   69,  130,  129,   69,  131,
      131,  131,  131,  132,   70,  137,   66,  150,   73,   73,
       73,   73,  133,   71,  138,  153,  146,  147,  154,  127,

      128,   69,   55,  157,  129,  155,   69,   74,  159,  156,
      132,   70,  137,  158,  170,  150,   75,  160,  161,  133,
       71,  138,  153,  162,  163,  154,  164,   55,  166,   69,
      157,  165,  155,  171,   74,  159,  156,  167,  168,  278,
      172,  158,  170,   75,  160,  161,  169,  173,  174,  175,
      162,  163,  176,  177,  164,  166,  178,  179,  165,  180,
      171,  121,  133,  189,  278,  167,  168,  172,  278,  278,
      181,  181,  181,  169,  173,  174,  175,  278,  278,  176,
      177,  278,  278,  278,  178,  179,  183,  180,  183,  133,
      189,  184,  184,  184,  184,  185,  191,  185,  138,  201,

      186,  186,  186,  186,   61,  131,  131,  131,  131,  131,
      131,  131,  131,  195,  196,  197,  198,  192,  199,  200,
      205,  193,  202,  187,  203,  138,  194,  201,  188,  204,
      204,  204,  206,  204,  207,  208,  209,  211,  212,  214,
      195,  196,  197,  198,  192,  199,  200,  205,  193,  213,
      202,  187,  203,  194,  215,  188,  216,  217,  278,  206,
      223,  207,  208,  209,  211,  278,  212,  214,  184,  184,
      184,  184,  278,  278,  278,  224,  213,  222,  225,  226,
      278,  278,  215,  216,  217,  218,  218,  218,  223,  219,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,

      220,  220,  220,  224,  222,  225,  226,  220,  220,  220,
      220,  220,  227,  228,  121,  229,  230,  231,  186,  186,
      186,  186,  234,  232,  232,  232,  238,  278,  238,  235,
      278,  239,  239,  239,  239,  240,  220,  220,  220,  220,
      227,  228,  229,  230,  231,  184,  184,  184,  184,  234,
      278,  278,  186,  186,  186,  186,  235,   61,  121,  125,
      278,  241,  240,  236,  126,  242,  128,  233,  233,  233,
      233,  129,  237,  245,  278,  246,  233,  233,  233,  233,
      233,  233,  278,  248,  243,  278,  249,  125,  241,  244,
      236,  126,  250,  242,  128,  251,  278,  278,  129,  237,

      245,   61,  246,  278,  233,  233,  233,  233,  233,  233,
      248,  278,  243,  249,  218,  218,  218,  244,  219,  250,
      218,  218,  218,  251,  219,  278,  278,  278,  252,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  253,  254,  278,  237,  220,  220,  220,
      220,  220,  255,  278,  255,  252,  278,  256,  256,  256,
      256,  257,  261,  257,  262,  264,  258,  258,  258,  258,
      253,  267,  254,  237,  263,  265,  220,  220,  220,  220,
      239,  239,  239,  239,  239,  239,  239,  239,  266,  261,
      268,  274,  262,  264,  269,  275,  278,  276,  259,  267,

      278,  263,  265,  260,  256,  256,  256,  256,  256,  256,
      256,  256,  278,  278,  277,  266,  278,  278,  268,  274,
      278,  269,  270,  275,  276,  278,  259,  271,  278,  278,
      260,  258,  258,  258,  258,  278,  278,  258,  258,  258,
      258,  277,  278,  278,  278,  278,  278,  278,  278,  278,
      270,  272,  278,  278,  271,  278,  273,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  272,
      278,  278,  278,  273,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   58,   58,   58,   58,   58,

       58,   58,   58,   60,   60,  278,   60,   60,  278,   60,
       60,   60,   60,   60,   79,   79,   79,   79,   60,   60,
      278,   60,  278,  278,   60,  136,  136,  136,  182,  182,
      190,  190,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,    7,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278
    } ;

static yyconst flex_int16_t yy_chk[933] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,   22,   22,   22,   22,   27,   27,   23,   31,  210,
        3,    4,   23,   24,   48,   24,   24,   24,   24,   60,

       25,   33,   25,   25,   25,   25,   33,  158,   24,   30,
       38,   32,   97,   36,   24,   25,   31,   38,   42,   30,
       32,   25,   48,   24,   30,   30,   24,   39,   43,   33,
       25,  232,   34,   33,   34,   71,   24,   30,   38,   32,
       36,   24,   60,   25,   38,   42,   30,   32,   25,   39,
       24,   30,   30,   24,   75,   43,   40,   25,   39,   34,
       35,   34,   71,   35,   40,   72,   35,   41,   44,  220,
      220,  220,   44,   46,  232,   80,   41,   39,   58,   54,
       46,   75,   41,   47,   40,   39,   46,   35,   81,   29,
       35,   82,   40,   35,   87,   41,   44,   61,   61,   61,

       44,   46,   80,   41,   63,   63,   63,   63,   46,   41,
       45,   45,   83,   46,   84,   45,   81,   63,   63,   82,
       85,   87,   45,   63,   89,   45,   45,   91,   61,   92,
       45,   28,   68,   18,   68,   68,   68,   68,   45,   45,
       83,   15,   84,   45,   13,   63,   63,   68,   85,   45,
       63,   89,   45,   45,   91,   61,   92,   45,   66,   66,
       66,   66,   12,   67,   11,   67,   67,   67,   67,   86,
       86,   66,   66,    7,   69,   68,   69,   66,   67,   69,
       69,   69,   69,   70,   67,   74,   73,   90,   73,   73,
       73,   73,   70,   67,   74,   93,   86,   86,   94,   66,

       66,   73,    6,   98,   66,   96,   67,   73,  100,   96,
       70,   67,   74,   99,  109,   90,   73,  101,  102,   70,
       67,   74,   93,  103,  104,   94,  106,    5,  107,   73,
       98,  106,   96,  110,   73,  100,   96,  108,  108,    0,
      111,   99,  109,   73,  101,  102,  108,  112,  113,  114,
      103,  104,  115,  116,  106,  107,  117,  118,  106,  119,
      110,  122,  132,  134,    0,  108,  108,  111,    0,    0,
      122,  122,  122,  108,  112,  113,  114,    0,    0,  115,
      116,    0,    0,    0,  117,  118,  124,  119,  124,  132,
      134,  124,  124,  124,  124,  127,  136,  127,  137,  146,

      127,  127,  127,  127,  122,  130,  130,  130,  130,  131,
      131,  131,  131,  139,  140,  142,  143,  136,  144,  145,
      151,  136,  147,  131,  149,  137,  136,  146,  131,  150,
      150,  150,  153,  150,  154,  155,  156,  161,  163,  165,
      139,  140,  142,  143,  136,  144,  145,  151,  136,  164,
      147,  131,  149,  136,  166,  131,  167,  168,    0,  153,
      171,  154,  155,  156,  161,    0,  163,  165,  183,  183,
      183,  183,    0,    0,    0,  172,  164,  170,  173,  174,
        0,    0,  166,  167,  168,  169,  169,  169,  171,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,

      169,  169,  169,  172,  170,  173,  174,  169,  169,  169,
      169,  169,  176,  177,  181,  178,  179,  180,  185,  185,
      185,  185,  190,  181,  181,  181,  193,    0,  193,  191,
        0,  193,  193,  193,  193,  194,  169,  169,  169,  169,
      176,  177,  178,  179,  180,  184,  184,  184,  184,  190,
        0,    0,  186,  186,  186,  186,  191,  181,  182,  184,
        0,  199,  194,  192,  184,  201,  186,  182,  182,  182,
      182,  186,  192,  205,    0,  208,  182,  182,  182,  182,
      182,  182,    0,  212,  204,    0,  213,  184,  199,  204,
      192,  184,  215,  201,  186,  217,    0,    0,  186,  192,

      205,  182,  208,    0,  182,  182,  182,  182,  182,  182,
      212,    0,  204,  213,  218,  218,  218,  204,  218,  215,
      219,  219,  219,  217,  219,  221,  221,  221,  223,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  230,  231,    0,  236,  221,  221,  221,
      221,  221,  234,    0,  234,  223,    0,  234,  234,  234,
      234,  235,  240,  235,  242,  244,  235,  235,  235,  235,
      230,  251,  231,  236,  243,  248,  221,  221,  221,  221,
      238,  238,  238,  238,  239,  239,  239,  239,  250,  240,
      252,  265,  242,  244,  253,  268,    0,  274,  239,  251,

        0,  243,  248,  239,  255,  255,  255,  255,  256,  256,
      256,  256,    0,    0,  275,  250,    0,    0,  252,  265,
        0,  253,  256,  268,  274,    0,  239,  256,    0,    0,
      239,  257,  257,  257,  257,    0,    0,  258,  258,  258,
      258,  275,    0,    0,    0,    0,    0,    0,    0,    0,
      256,  258,    0,    0,  256,    0,  258,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  258,
        0,    0,    0,  258,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  280,  280,  280,  280,  280,

      280,  280,  280,  281,  281,    0,  281,  281,    0,  281,
      281,  281,  281,  281,  282,  282,  282,  282,  283,  283,
        0,  283,    0,    0,  283,  284,  284,  284,  285,  285,
      286,  286,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ebasic.l"
#line 2 "ebasic.l"
#include "parser.h"
int line_num = 1;

void yyget_INTEGER(YYSTYPE*, char*, size_t);
void yyget_REAL (YYSTYPE*, char*, size_t);
void yyget_STRING(YYSTYPE*, char*, size_t);

#define yyget_IDENTIFIER yyget_STRING
#define SAVE_VALUE(type)					\
{						\
        yyget_##type(&yylval, yytext, yyleng);	\
        return  type;				\
}

void yyget_INTEGER(YYSTYPE *outval, char *text, size_t len) {
	outval->integer = atoi(text);
}

void yyget_REAL(YYSTYPE *outval, char *text, size_t len) {
	outval->real = atof(text);
}

void yyget_STRING(YYSTYPE *outval, char *text, size_t len) {
	outval->string = text;
}


#line 790 "lexer.c"

#define INITIAL 0
#define COMMENTS 1
#define SINGLELINECOMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 50 "ebasic.l"


#line 982 "lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 853 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 "ebasic.l"
{BEGIN(COMMENTS);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "ebasic.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 54 "ebasic.l"
{ ++line_num; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 55 "ebasic.l"
{ ++line_num;BEGIN(INITIAL); return NEWLINE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "ebasic.l"
;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 58 "ebasic.l"
{ ++line_num; return NEWLINE; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 59 "ebasic.l"
;
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 60 "ebasic.l"
return REM;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "ebasic.l"
SAVE_VALUE(STRING);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "ebasic.l"
SAVE_VALUE(INTEGER); 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "ebasic.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "ebasic.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "ebasic.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "ebasic.l"
SAVE_VALUE(REAL); 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "ebasic.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 "ebasic.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 "ebasic.l"
SAVE_VALUE(REAL); 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "ebasic.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "ebasic.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 75 "ebasic.l"
return AND;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "ebasic.l"
return OR;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 77 "ebasic.l"
return NOT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 78 "ebasic.l"
return NEQ;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 79 "ebasic.l"
return LEQ;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 80 "ebasic.l"
return GEQ;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 81 "ebasic.l"
return LT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 82 "ebasic.l"
return GT;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 83 "ebasic.l"
return EQ;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 84 "ebasic.l"
return POW;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "ebasic.l"
return COMMA;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "ebasic.l"
return ADD;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "ebasic.l"
return SUB;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "ebasic.l"
return MULT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "ebasic.l"
return DIV;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "ebasic.l"
return MOD;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "ebasic.l"
return SLBRACE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "ebasic.l"
return SRBRACE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "ebasic.l"
return LPAREN;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 94 "ebasic.l"
return RPAREN;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 95 "ebasic.l"
return ELSE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 96 "ebasic.l"
return SEND;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 97 "ebasic.l"
return RECV;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 98 "ebasic.l"
return SENDRECV;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 99 "ebasic.l"
return TOFROM;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 100 "ebasic.l"
return SYNC;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 101 "ebasic.l"
return BCAST;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 102 "ebasic.l"
return REDUCE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 103 "ebasic.l"
return INTO;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 104 "ebasic.l"
return SUM;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 105 "ebasic.l"
return MIN;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 106 "ebasic.l"
return MAX;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 107 "ebasic.l"
return PROD;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 108 "ebasic.l"
return DIM;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 109 "ebasic.l"
return SDIM;
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 110 "ebasic.l"
return ENDIF;
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 111 "ebasic.l"
return ENDDO;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 112 "ebasic.l"
return DO;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 113 "ebasic.l"
return WHILE;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 114 "ebasic.l"
return LET;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 115 "ebasic.l"
return STOP;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 116 "ebasic.l"
return FOR;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 117 "ebasic.l"
return TO;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 118 "ebasic.l"
return FROM;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 119 "ebasic.l"
return NEXT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 120 "ebasic.l"
return GOTO;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 121 "ebasic.l"
return IF;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 122 "ebasic.l"
return THEN;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 123 "ebasic.l"
return PRINT;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 124 "ebasic.l"
return INPUT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 125 "ebasic.l"
return COREID;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 126 "ebasic.l"
return NUMCORES;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 127 "ebasic.l"
return RANDOM;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 128 "ebasic.l"
return SQRT;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 129 "ebasic.l"
return SIN;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 130 "ebasic.l"
return COS;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 131 "ebasic.l"
return TAN;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 132 "ebasic.l"
return ASIN;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 133 "ebasic.l"
return ACOS;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 134 "ebasic.l"
return ATAN;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 135 "ebasic.l"
return SINH;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 136 "ebasic.l"
return COSH;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 137 "ebasic.l"
return TANH;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 138 "ebasic.l"
return FLOOR;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 139 "ebasic.l"
return CEIL;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 140 "ebasic.l"
return LOG;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 141 "ebasic.l"
return LOG10;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 142 "ebasic.l"
BEGIN(SINGLELINECOMMENT);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 144 "ebasic.l"
return yytext[0];
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 146 "ebasic.l"
SAVE_VALUE(IDENTIFIER);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 147 "ebasic.l"
ECHO;
	YY_BREAK
#line 1522 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENTS):
case YY_STATE_EOF(SINGLELINECOMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 278);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 147 "ebasic.l"



