#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[325] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  104,  103,
       13,   12,  103,   28,  103,  100,   43,  103,   46,   47,
       41,   39,   37,   40,  101,   42,   18,   17,   38,  101,
       32,   34,   33,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,   44,   45,   36,    7,    5,    7,    6,   11,    9,
       10,    8,   12,   29,    0,   15,    0,    0,   36,   21,
        3,   99,   22,   18,    0,    0,   18,   18,    0,   17,
       17,   17,    0,   30,   35,   31,    0,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,   78,  102,    0,  102,  102,  102,  102,
      102,  102,   27,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,   74,  102,  102,    4,   19,    0,    0,
        0,   21,   21,    0,   22,   22,    0,   20,   18,   18,
       18,    0,   16,   17,   17,   17,    0,    0,  102,   26,
      102,  102,  102,   87,   50,   68,  102,  102,  102,  102,
       73,  102,  102,  102,  102,   71,   97,   66,   65,  102,
      102,   28,  102,  102,  102,   14,  102,  102,   86,  102,
      102,   64,   88,  102,  102,  102,  102,    0,    0,    0,
       21,    0,   22,   20,   20,   18,    0,    0,   16,    0,

       16,   17,    0,    1,    0,    2,   90,   89,   91,   96,
       93,   55,  102,  102,  102,   75,   77,  102,   63,  102,
       76,   52,  102,   67,  102,   14,   14,   14,   14,  102,
       69,   92,   85,   72,   94,   79,  102,   48,  102,    0,
        0,    0,    0,   16,   16,    0,   23,   16,  102,   49,
       95,   81,   98,   80,  102,  102,  102,   70,    0,   24,
        0,   25,   23,   23,   16,  102,   84,   51,   59,   24,
       24,   25,   25,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

       57,  102,   56,   60,   61,  102,  102,  102,  102,  102,
      102,   82,  102,   53,  102,   62,  102,  102,  102,  102,
       54,   83,   58,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,   10,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,   30,   10,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   40,
       55,   56,   57,   58,   59,   10,   60,   61,   62,   63,

       64,   65,   66,   67,   68,   40,   40,   69,   70,   71,
       72,   73,   74,   75,   76,   77,   78,   79,   80,   81,
       82,   40,   10,   10,   10,   10,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[83] =
    {   0,
        1,    2,    3,    2,    1,    4,    4,    5,    4,    4,
        4,    6,    4,    4,    4,    4,    4,    4,    7,    4,
        8,    8,    8,    9,    4,    4,    4,    4,    4,    5,
        8,    8,    9,    9,    9,    8,   10,   10,   10,   10,
       10,   10,   11,   10,   10,   10,   11,   10,   11,   10,
       11,   10,   11,   10,    4,    5,    4,    4,   10,    8,
        8,    9,    9,    9,    8,   10,   10,   10,   10,   10,
       11,   10,   10,   10,   11,   10,   11,   10,   11,   10,
       11,   10
    } ;

static yyconst flex_int16_t yy_base[338] =
    {   0,
        0,    0,   80,   81,  283,  282,   83,   85,  280,  931,
      931,  931,  275,  249,  267,  931,  931,  198,  931,  931,
      238,  931,  931,  931,   76,   86,   88,   95,  931,  931,
       65,  211,   74,   72,    0,   78,   69,   87,  124,   81,
      111,  123,  141,  126,   99,  104,  146,  158,  180,  221,
      124,  931,  931,  931,  931,  931,  200,  931,  931,  931,
      931,  931,  931,  931,  211,  931,  119,  191,  931,  227,
      931,  931,  235,  260,  284,  207,  196,  147,  184,  290,
      219,  148,  175,  931,  931,  931,  171,    0,  150,  152,
      166,  207,  222,  197,  228,  224,  239,  235,  257,  258,

      269,  274,  272,    0,  278,  129,  273,  291,  279,  290,
      281,  292,    0,  298,  293,  303,  304,  296,  300,  309,
      314,  315,  330,  335,  324,  337,  931,  931,  366,    0,
      374,  931,  931,  385,  931,  931,  389,  393,  341,  931,
      352,    0,  399,  349,  931,  363,  175,  160,  372,    0,
      380,  381,  384,  388,    0,    0,  393,   85,  383,  389,
        0,  393,  392,  387,  394,    0,  118,    0,    0,  390,
      406,    0,  400,  411,  412,  476,  419,  439,  409,  449,
      454,    0,  462,  464,  461,  475,  471,  499,  544,  492,
      521,  525,  548,  931,  931,  931,  478,  479,  513,  598,

      484,  931,  124,  931,  123,  931,    0,    0,    0,    0,
        0,    0,  491,  523,  513,    0,    0,  515,    0,  103,
        0,    0,  524,    0,  530,  591,  621,  239,  626,  536,
        0,    0,    0,    0,    0,    0,  554,    0,  546,  127,
        0,  641,  650,  553,  931,  626,  654,  617,   31,    0,
        0,    0,    0,    0,  618,  618,  627,    0,  670,  677,
      681,  685,  931,  931,  931,  696,    0,    0,    0,  931,
      931,  931,  931,  634,  643,  662,  662,  650,  687,  685,
      673,  693,  682,  699,  682,  694,  699,  695,  699,  705,
      722,  715,  718,  736,  740,  727,  735,  727,  731,  736,

        0,  748,  736,    0,    0,  751,  747,  739,  742,  755,
      756,    0,  759,    0,  758,    0,  762,  762,  752,  750,
        0,    0,    0,  931,  829,  840,  848,  859,  863,  870,
      875,  877,  879,  888,  899,  909,  919
    } ;

static yyconst flex_int16_t yy_def[338] =
    {   0,
      324,    1,  325,  325,  325,  325,  326,  326,  324,  324,
      324,  324,  324,  324,  327,  324,  324,  328,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  327,  324,  328,  330,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  331,  324,
      324,  324,  324,  324,  324,  324,  324,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  328,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  324,  324,  328,  332,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  333,  331,  324,  324,  324,  334,  335,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  336,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  328,  328,  324,
      324,  324,  324,  324,  324,  324,  333,  333,  324,  324,

      324,  324,  334,  324,  335,  324,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  337,  337,  337,  336,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  328,
      189,  324,  324,  324,  324,  324,  324,  324,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  324,  324,
      324,  324,  324,  324,  324,  329,  329,  329,  329,  324,
      324,  324,  324,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,    0,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324
    } ;

static yyconst flex_int16_t yy_nxt[1014] =
    {   0,
       10,   11,   12,   10,   13,   11,   14,   15,   16,   10,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   28,   28,   29,   30,   31,   32,   33,   10,
       34,   35,   36,   37,   38,   39,   40,   35,   41,   35,
       42,   43,   44,   45,   46,   35,   47,   48,   49,   50,
       35,   51,   35,   35,   52,   10,   53,   54,   35,   34,
       35,   36,   37,   38,   39,   40,   35,   41,   42,   43,
       44,   45,   46,   35,   47,   48,   49,   50,   35,   51,
       35,   35,   56,   56,   60,   61,   60,   61,   62,  266,
       62,   83,   84,   64,   57,   57,   70,   70,   70,   70,

       71,   86,   87,   95,   89,   72,   73,   96,   74,   74,
       74,   75,   93,   73,   90,   80,   80,   80,   80,   91,
       92,   94,   76,  253,  103,  206,  204,   97,   77,   76,
      128,   98,   95,   89,  106,   81,   96,   78,  128,  220,
       79,   93,   90,  213,   82,  113,  104,   91,   92,   94,
      114,   76,  103,  105,   99,   97,   77,  107,   76,   98,
      111,  126,  206,   81,  100,   78,  108,  101,   79,  112,
      102,  109,   82,  113,   68,  104,  115,  204,  114,  110,
      116,  105,   68,   99,   68,  150,  107,  141,  146,  111,
      126,  117,  100,  149,  108,  101,  118,  112,  102,  148,

      109,  147,  142,  119,  151,  115,  120,  121,  110,  116,
      122,  129,  129,  129,  150,  141,  146,  123,   66,  127,
      117,  149,  137,  124,  137,  118,  125,  138,  138,  138,
      138,  119,  106,  151,  120,  121,  139,  152,   85,  122,
      324,  324,  324,  130,  154,  140,  123,   70,   70,   70,
       70,  124,   69,   68,  125,   70,   70,   70,   70,  144,
      153,  131,  132,  155,  139,  156,  152,  133,  145,  134,
      135,  130,  154,  140,   66,  136,   64,   63,   73,  324,
       74,   74,   74,   75,   58,   58,  157,  144,  158,  153,
      131,  132,  155,  156,   76,  133,  145,  159,  134,  135,

       77,  160,   73,  136,   75,   75,   75,   75,   73,   78,
       80,   80,   80,   80,  157,  161,  158,  162,   76,  324,
      163,  166,  164,   76,   76,  159,  165,  167,   77,  160,
       81,  168,  169,  170,  171,  175,  173,   78,  179,   82,
      172,  174,  178,  161,  176,  162,  180,   76,  163,  166,
      164,  177,  181,   76,  165,  182,  167,  183,   81,  168,
      169,  170,  171,  175,  184,  173,  179,   82,  172,  174,
      185,  178,  176,  186,  180,  187,  324,  128,  324,  177,
      181,  324,  324,  182,  324,  183,  188,  188,  188,  190,
      140,  190,  196,  184,  191,  191,  191,  191,  145,  185,

      192,  186,  192,  202,  187,  193,  193,  193,  193,  138,
      138,  138,  138,  138,  138,  138,  138,  198,  140,  207,
      196,   68,  208,  209,  210,  211,  145,  212,  194,  324,
      214,  202,  215,  195,  216,  217,  218,  219,  221,  199,
      222,  324,  223,  200,  224,  225,  232,  207,  201,  324,
      208,  209,  210,  324,  211,  324,  212,  194,  214,  324,
      215,  195,  216,  217,  218,  219,  221,  199,  230,  222,
      223,  200,  324,  224,  225,  232,  201,  226,  226,  226,
      231,  227,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  230,  233,  234,  235,

      228,  228,  228,  228,  228,  228,  236,  237,  231,  238,
      128,  239,  191,  191,  191,  191,  324,  324,  324,  240,
      240,  240,  242,  243,  248,  233,  234,  324,  235,  249,
      228,  228,  228,  228,  236,  237,  324,  324,  238,  239,
      324,  191,  191,  191,  191,  193,  193,  193,  193,  324,
      242,  243,  248,  244,   68,  128,  132,  250,  249,  251,
      324,  133,  245,  252,  241,  241,  241,  241,  193,  193,
      193,  193,  254,  255,  241,  241,  241,  241,  241,  241,
      258,  244,  256,  135,  324,  132,  250,  251,  136,  133,
      245,  252,  226,  226,  226,  324,  227,  257,  324,   68,

      254,  255,  245,  241,  241,  241,  241,  241,  241,  258,
      256,  324,  135,  246,  324,  246,  136,  324,  247,  247,
      247,  247,  226,  226,  226,  257,  227,  324,  324,  324,
      245,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  247,  247,  247,  247,
      228,  228,  228,  228,  228,  228,  259,  265,  259,  267,
      268,  260,  260,  260,  260,  261,  280,  261,  269,  324,
      262,  262,  262,  262,  247,  247,  247,  247,  324,  324,
      228,  228,  228,  228,  284,  265,  281,  267,  268,  263,
      260,  260,  260,  260,  264,  280,  269,  260,  260,  260,

      260,  262,  262,  262,  262,  262,  262,  262,  262,  282,
      324,  283,  270,  284,  281,  287,  324,  271,  263,  288,
      272,  285,  264,  291,  294,  273,  289,  274,  275,  297,
      290,  292,  293,  298,  276,  324,  295,  282,  277,  283,
      286,  270,  278,  279,  287,  271,  296,  288,  299,  272,
      285,  291,  294,  273,  300,  289,  274,  275,  297,  290,
      292,  293,  298,  276,  295,  301,  277,  302,  286,  303,
      278,  279,  304,  306,  296,  305,  299,  307,  308,  309,
      310,  324,  311,  300,  312,  313,  324,  314,  315,  316,
      317,  318,  319,  301,  320,  302,  321,  324,  303,  322,

      323,  304,  306,  305,  324,  307,  308,  309,  324,  310,
      311,  324,  324,  312,  313,  314,  315,  324,  316,  317,
      318,  319,  324,  320,  324,  321,  324,  322,  323,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   65,   65,   65,   65,   65,   65,   65,   65,   67,
       67,  324,   67,   67,  324,   67,   67,   67,   67,   67,
       88,   88,   88,   88,   67,   67,  324,   67,  324,  324,
       67,  143,  143,  143,  189,  189,  197,  197,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  205,

      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
        9,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324
    } ;

static yyconst flex_int16_t yy_chk[1014] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    7,    7,    8,    8,    7,  249,
        8,   31,   31,   31,    3,    4,   25,   25,   25,   25,

       26,   33,   33,   37,   34,   26,   27,   37,   27,   27,
       27,   27,   36,   28,   34,   28,   28,   28,   28,   34,
       34,   36,   27,  220,   40,  205,  203,   38,   27,   28,
       67,   38,   37,   34,   42,   28,   37,   27,  240,  167,
       27,   36,   34,  158,   28,   45,   41,   34,   34,   36,
       46,   27,   40,   41,   39,   38,   27,   42,   28,   38,
       44,   51,  148,   28,   39,   27,   42,   39,   27,   44,
       39,   43,   28,   45,   67,   41,   47,  147,   46,   43,
       47,   41,  240,   39,  106,   90,   42,   78,   82,   44,
       51,   48,   39,   89,   42,   39,   48,   44,   39,   87,

       43,   83,   79,   48,   91,   47,   48,   48,   43,   47,
       49,   68,   68,   68,   90,   78,   82,   49,   65,   57,
       48,   89,   76,   49,   76,   48,   49,   76,   76,   76,
       76,   48,   50,   91,   48,   48,   77,   92,   32,   49,
      228,  228,  228,   68,   94,   77,   49,   70,   70,   70,
       70,   49,   21,   18,   49,   73,   73,   73,   73,   81,
       93,   70,   70,   95,   77,   96,   92,   70,   81,   73,
       73,   68,   94,   77,   15,   73,   14,   13,   74,    9,
       74,   74,   74,   74,    6,    5,   97,   81,   98,   93,
       70,   70,   95,   96,   74,   70,   81,   99,   73,   73,

       74,  100,   75,   73,   75,   75,   75,   75,   80,   74,
       80,   80,   80,   80,   97,  101,   98,  102,   75,    0,
      103,  107,  105,   74,   80,   99,  105,  108,   74,  100,
       80,  109,  110,  111,  112,  115,  114,   74,  118,   80,
      112,  114,  117,  101,  116,  102,  119,   75,  103,  107,
      105,  116,  120,   80,  105,  121,  108,  122,   80,  109,
      110,  111,  112,  115,  123,  114,  118,   80,  112,  114,
      124,  117,  116,  125,  119,  126,    0,  129,    0,  116,
      120,    0,    0,  121,    0,  122,  129,  129,  129,  131,
      139,  131,  141,  123,  131,  131,  131,  131,  144,  124,

      134,  125,  134,  146,  126,  134,  134,  134,  134,  137,
      137,  137,  137,  138,  138,  138,  138,  143,  139,  149,
      141,  129,  151,  152,  153,  154,  144,  157,  138,    0,
      159,  146,  160,  138,  162,  163,  164,  165,  170,  143,
      171,    0,  173,  143,  174,  175,  179,  149,  143,    0,
      151,  152,  153,    0,  154,    0,  157,  138,  159,    0,
      160,  138,  162,  163,  164,  165,  170,  143,  177,  171,
      173,  143,    0,  174,  175,  179,  143,  176,  176,  176,
      178,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  177,  180,  181,  183,

      176,  176,  176,  176,  176,  176,  184,  185,  178,  186,
      188,  187,  190,  190,  190,  190,    0,    0,    0,  188,
      188,  188,  197,  198,  201,  180,  181,    0,  183,  213,
      176,  176,  176,  176,  184,  185,    0,    0,  186,  187,
        0,  191,  191,  191,  191,  192,  192,  192,  192,    0,
      197,  198,  201,  199,  188,  189,  191,  214,  213,  215,
        0,  191,  199,  218,  189,  189,  189,  189,  193,  193,
      193,  193,  223,  225,  189,  189,  189,  189,  189,  189,
      239,  199,  230,  193,    0,  191,  214,  215,  193,  191,
      199,  218,  226,  226,  226,    0,  226,  237,    0,  189,

      223,  225,  244,  189,  189,  189,  189,  189,  189,  239,
      230,    0,  193,  200,    0,  200,  193,    0,  200,  200,
      200,  200,  227,  227,  227,  237,  227,  229,  229,  229,
      244,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  246,  246,  246,  246,
      229,  229,  229,  229,  229,  229,  242,  248,  242,  255,
      256,  242,  242,  242,  242,  243,  274,  243,  257,    0,
      243,  243,  243,  243,  247,  247,  247,  247,    0,    0,
      229,  229,  229,  229,  278,  248,  275,  255,  256,  247,
      259,  259,  259,  259,  247,  274,  257,  260,  260,  260,

      260,  261,  261,  261,  261,  262,  262,  262,  262,  276,
        0,  277,  260,  278,  275,  280,    0,  260,  247,  281,
      262,  279,  247,  283,  285,  262,  282,  266,  266,  288,
      282,  284,  284,  289,  266,    0,  286,  276,  266,  277,
      279,  260,  266,  266,  280,  260,  287,  281,  290,  262,
      279,  283,  285,  262,  291,  282,  266,  266,  288,  282,
      284,  284,  289,  266,  286,  292,  266,  293,  279,  294,
      266,  266,  295,  297,  287,  296,  290,  298,  299,  300,
      302,    0,  303,  291,  306,  307,    0,  308,  309,  310,
      311,  313,  315,  292,  317,  293,  318,    0,  294,  319,

      320,  295,  297,  296,    0,  298,  299,  300,    0,  302,
      303,    0,    0,  306,  307,  308,  309,    0,  310,  311,
      313,  315,    0,  317,    0,  318,    0,  319,  320,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  327,  327,  327,  327,  327,  327,  327,  327,  328,
      328,    0,  328,  328,    0,  328,  328,  328,  328,  328,
      329,  329,  329,  329,  330,  330,    0,  330,    0,    0,
      330,  331,  331,  331,  332,  332,  333,  333,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  335,

      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "epython.l"
#line 2 "epython.l"
#include "parser.h"
#include "stack.h"

static const unsigned int TAB_WIDTH = 4;

int line_num = 0, indent_caller;
char * parsing_filename=NULL;
int line_indent=0, fake_outdent_symbol=0;

extern struct stack_t indent_stack, filenameStack, lineNumberStack;

void yyget_INTEGER(YYSTYPE*, char*, size_t);
void yyget_REAL (YYSTYPE*, char*, size_t);
void yyget_STRING(YYSTYPE*, char*, size_t);

#define yyget_IDENTIFIER yyget_STRING
#define SAVE_VALUE(type)					\
{						\
        yyget_##type(&yylval, yytext, yyleng);	\
        return  type;				\
}

void yyget_INTEGER(YYSTYPE *outval, char *text, size_t len) {
	outval->integer = atoi(text);
}

void yyget_REAL(YYSTYPE *outval, char *text, size_t len) {
	outval->real = atof(text);
}

void yyget_STRING(YYSTYPE *outval, char *text, size_t len) {
	outval->string = text;
}
/* Python indentation handling based upon code at https://github.com/lucasb-eyer/flex-bison-indentation and 
http://www.benbarbour.com/implementing-python-style-indention-syntax-using-flex-bison-or-lexyacc */



#line 838 "lexer.c"

#define INITIAL 0
#define COMMENTS 1
#define SINGLELINECOMMENT 2
#define INDENT_MODE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 62 "epython.l"


#line 1031 "lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 325 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 931 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 64 "epython.l"
{ 
									if (parsing_filename != NULL) {
										pushIdentifier(&filenameStack, parsing_filename); 
										push(&lineNumberStack, line_num);
										free(parsing_filename);
									}
									parsing_filename=(char*) malloc(yyleng-3);
									strncpy(parsing_filename, &yytext[3], yyleng-4);
									parsing_filename[yyleng-4]='\0';									
									line_num=1; 
								}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 75 "epython.l"
{
									if (getStackSize(&filenameStack) > 0) {
										parsing_filename=popIdentifier(&filenameStack);
										line_num=pop(&lineNumberStack);
									}									
								}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 82 "epython.l"
{BEGIN(COMMENTS);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "epython.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 84 "epython.l"
{ ++line_num; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 85 "epython.l"
{ ++line_num;BEGIN(INITIAL); return NEWLINE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 86 "epython.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "epython.l"
{ line_indent++; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "epython.l"
{ line_indent+=TAB_WIDTH; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 90 "epython.l"
{ line_indent=0; }
	YY_BREAK
case YY_STATE_EOF(INDENT_MODE):
#line 91 "epython.l"
{ 	if (peek(&indent_stack) > 0) {
						pop(&indent_stack);
						if (line_indent < peek(&indent_stack)) {
							int i;
                            unput('\n');
                            for (i=0;i<peek(&indent_stack);i++) unput(' ');                            
                        } else {											
							BEGIN(indent_caller);
						}
						return OUTDENT;						
					} else {
						yyterminate();
					}					 
				}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 105 "epython.l"
{
					if (!fake_outdent_symbol) unput(*yytext);					
					fake_outdent_symbol=0;
					if (line_indent > 0 && line_indent > peek(&indent_stack)) {
						push(&indent_stack, line_indent);						
						BEGIN(indent_caller);						
						return INDENT;
					} else if (line_indent < peek(&indent_stack)) {
						pop(&indent_stack);
						if (line_indent != peek(&indent_stack)) {
							int i;
							for(i=0;i<line_indent;i++) unput(' ');
                            unput('\n');                            
                            unput('.');                          
                            fake_outdent_symbol=1;
                            for(i=0;i<peek(&indent_stack);i++) unput(' ');
                            unput('\n');
						} else {
							BEGIN(indent_caller);
						}
						return OUTDENT;
					} else {
						BEGIN(indent_caller);
					}
				}									
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 131 "epython.l"
{ ++line_num; line_indent=0; indent_caller = YY_START; BEGIN(INDENT_MODE); return NEWLINE; }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 132 "epython.l"
;
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 133 "epython.l"
return REM;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 134 "epython.l"
SAVE_VALUE(STRING);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 136 "epython.l"
SAVE_VALUE(INTEGER); 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 137 "epython.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 138 "epython.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 139 "epython.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 141 "epython.l"
SAVE_VALUE(REAL); 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 142 "epython.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 143 "epython.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 144 "epython.l"
SAVE_VALUE(REAL); 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 145 "epython.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 146 "epython.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 148 "epython.l"
return AND;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 149 "epython.l"
return OR;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 150 "epython.l"
return NOT;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 151 "epython.l"
return NEQ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 152 "epython.l"
return LEQ;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 153 "epython.l"
return GEQ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 154 "epython.l"
return LT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 155 "epython.l"
return GT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 156 "epython.l"
return ASSGN;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 157 "epython.l"
return EQ;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 158 "epython.l"
return POW;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 159 "epython.l"
return COMMA;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 160 "epython.l"
return COLON;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 161 "epython.l"
return ADD;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 162 "epython.l"
return SUB;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 163 "epython.l"
return MULT;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 164 "epython.l"
return DIV;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 165 "epython.l"
return MOD;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 166 "epython.l"
return SLBRACE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 167 "epython.l"
return SRBRACE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 168 "epython.l"
return LPAREN;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 169 "epython.l"
return RPAREN;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 170 "epython.l"
return TRUE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 171 "epython.l"
return FALSE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 172 "epython.l"
return DEF;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 173 "epython.l"
return RET;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 174 "epython.l"
return NONE;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 175 "epython.l"
return EPY_I_ISHOST;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 176 "epython.l"
return EPY_I_ISDEVICE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 177 "epython.l"
return ELSE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 178 "epython.l"
return EPY_I_SEND;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 179 "epython.l"
return EPY_I_RECV;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 180 "epython.l"
return EPY_I_SENDRECV;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 181 "epython.l"
return TOFROM;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 182 "epython.l"
return EPY_I_SYNC;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 183 "epython.l"
return EPY_I_BCAST;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 184 "epython.l"
return EPY_I_REDUCE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 185 "epython.l"
return INTO;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 186 "epython.l"
return SUM;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 187 "epython.l"
return MIN;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 188 "epython.l"
return MAX;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 189 "epython.l"
return PROD;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 190 "epython.l"
return DIM;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 191 "epython.l"
return SDIM;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 192 "epython.l"
return WHILE;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 193 "epython.l"
return LET;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 194 "epython.l"
return STOP;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 195 "epython.l"
return FOR;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 196 "epython.l"
return TO;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 197 "epython.l"
return FROM;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 198 "epython.l"
return NEXT;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 199 "epython.l"
return GOTO;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 200 "epython.l"
return IF;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 201 "epython.l"
return THEN;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 202 "epython.l"
return PRINT;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 203 "epython.l"
return INPUT;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 204 "epython.l"
return EPY_I_COREID;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 205 "epython.l"
return EPY_I_NUMCORES;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 206 "epython.l"
return RANDOM;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 207 "epython.l"
return SQRT;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 208 "epython.l"
return SIN;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 209 "epython.l"
return COS;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 210 "epython.l"
return TAN;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 211 "epython.l"
return ASIN;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 212 "epython.l"
return ACOS;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 213 "epython.l"
return ATAN;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 214 "epython.l"
return SINH;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 215 "epython.l"
return COSH;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 216 "epython.l"
return TANH;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 217 "epython.l"
return FLOOR;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 218 "epython.l"
return CEIL;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 219 "epython.l"
return LOG;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 220 "epython.l"
return LOG10;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 221 "epython.l"
BEGIN(SINGLELINECOMMENT);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 222 "epython.l"
BEGIN(SINGLELINECOMMENT);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 224 "epython.l"
return yytext[0];
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 226 "epython.l"
SAVE_VALUE(IDENTIFIER);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 227 "epython.l"
ECHO;
	YY_BREAK
#line 1693 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENTS):
case YY_STATE_EOF(SINGLELINECOMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 325 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 325 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 324);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 227 "epython.l"



