#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 96
#define YY_END_OF_BUFFER 97
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[290] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   97,   96,
       11,   10,   96,   26,   96,   93,   41,   96,   44,   45,
       39,   37,   35,   38,   94,   40,   16,   15,   36,   94,
       30,   32,   31,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   42,   43,   34,    5,    3,    5,    4,    9,
        7,    8,    6,   10,   27,    0,   13,    0,    0,   34,
       19,    1,   92,   20,   16,    0,    0,   16,   16,    0,
       15,   15,   15,   28,   33,   29,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       71,   95,   95,    0,   95,   95,   95,   95,   95,   95,
       95,   25,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   67,   95,    2,   17,    0,    0,
        0,   19,   19,    0,   20,   20,    0,   18,   16,   16,
       16,    0,   14,   15,   15,   15,   95,   24,   95,   95,
       95,   95,   95,   80,   61,   95,   95,   66,   95,   95,
       95,   95,   95,   95,   64,   90,   59,   58,   95,   26,
       95,   95,   95,   95,   95,   95,   12,   95,   95,   79,
       95,   95,   57,   95,   81,   95,   95,   95,    0,    0,
        0,   19,    0,   20,   18,   18,   16,    0,    0,   14,

        0,   14,   15,   83,   82,   84,   95,   89,   95,   86,
       48,   95,   68,   70,   95,   56,   95,   95,   95,   69,
       95,   95,   60,   95,   50,   95,   12,   12,   12,   12,
       62,   49,   85,   78,   65,   53,   87,   72,   95,   95,
        0,    0,    0,    0,   14,   14,    0,   21,   14,   54,
       95,   88,   74,   95,   95,   91,   95,   73,   95,   95,
       95,   95,   63,    0,   22,    0,   23,   21,   21,   14,
       75,   95,   46,   95,   77,   55,   95,   52,   22,   22,
       23,   23,   95,   95,   95,   47,   76,   51,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,   10,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,   30,   10,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   40,
       55,   56,   57,   58,   40,   10,   59,   60,   61,   62,

       63,   64,   65,   66,   67,   40,   40,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   40,   10,   10,   10,   10,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[82] =
    {   0,
        1,    2,    3,    2,    1,    4,    4,    5,    4,    4,
        4,    6,    4,    4,    4,    4,    4,    4,    7,    4,
        8,    8,    8,    9,    4,    4,    4,    4,    4,    5,
        8,    8,    9,    9,    9,    8,   10,   10,   10,   10,
       10,   10,   11,   10,   10,   10,   11,   10,   11,   10,
       11,   10,   11,   10,    4,    5,    4,    4,    8,    8,
        9,    9,    9,    8,   10,   10,   10,   10,   10,   11,
       10,   10,   10,   11,   10,   11,   10,   11,   10,   11,
       10
    } ;

static yyconst flex_int16_t yy_base[301] =
    {   0,
        0,    0,   79,   80,  284,  274,   82,   84,  274,  873,
      873,  873,  270,  226,  203,  873,  873,  144,  873,  873,
      182,  873,  873,  873,   75,   85,   87,   94,  873,  873,
       63,  154,  150,   71,   60,   68,   63,   66,  101,   80,
        0,   90,  124,  122,  135,   78,  102,  142,  179,  165,
      162,  118,  873,  873,  873,  873,  873,  143,  873,  873,
      873,  873,  873,  873,  873,  135,  873,  146,  169,  873,
      240,  873,  873,  247,  216,  277,  298,  166,  125,  108,
      304,  176,  142,  873,  873,  873,    0,  144,  146,  160,
      173,  188,  181,  211,  152,  175,  201,  218,  223,  229,

        0,  257,  275,   67,  231,  252,  238,  254,  277,  282,
      290,    0,  299,  291,  302,  307,  299,  305,  302,  306,
      309,  309,  310,  320,  320,  321,  873,  873,  370,    0,
      378,  873,  873,  387,  873,  873,  391,  395,  312,  873,
      327,    0,  379,  356,  873,  366,  373,    0,  379,  380,
      377,  386,  369,  392,    0,  402,  384,    0,  393,  395,
      390,  397,  407,  400,    0,   79,    0,    0,  396,    0,
      413,  410,  423,  426,  413,  419,  495,  431,  427,  452,
      443,  471,    0,  484,  488,  485,  482,  489,  515,  560,
      454,  537,  460,  544,  873,  873,  873,  490,  497,  529,

      609,  506,  873,    0,    0,    0,  499,    0,  510,    0,
        0,  516,    0,    0,  527,    0,  535,  539,   68,    0,
      544,  550,    0,  558,    0,  556,  632,  637,  383,  642,
        0,  563,    0,    0,    0,    0,    0,    0,  603,  565,
      174,    0,  657,  666,  614,  873,  510,  671,  635,    0,
      643,    0,    0,  644,  637,    0,  649,    0,  659,  667,
      669,  664,    0,  693,  719,  697,  725,  873,  873,  873,
        0,  675,    0,  674,    0,    0,  677,    0,  873,  873,
      873,  873,  687,  676,  674,    0,    0,    0,  873,  793,
      804,  812,  823,  827,  834,  839,  841,  843,  851,  861

    } ;

static yyconst flex_int16_t yy_def[301] =
    {   0,
      289,    1,  290,  290,  290,  290,  291,  291,  289,  289,
      289,  289,  289,  289,  292,  289,  289,  293,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  292,  289,  293,  295,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  296,
      289,  289,  289,  289,  289,  289,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  293,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  289,  289,  293,  297,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  298,  296,  289,  289,  289,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  299,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  293,  293,
      289,  289,  289,  289,  289,  289,  289,  298,  298,  289,

      289,  289,  289,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  300,  300,  300,  299,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      293,  190,  289,  289,  289,  289,  289,  289,  289,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  289,  289,  289,  289,  289,  289,  289,
      294,  294,  294,  294,  294,  294,  294,  294,  289,  289,
      289,  289,  294,  294,  294,  294,  294,  294,    0,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289

    } ;

static yyconst flex_int16_t yy_nxt[955] =
    {   0,
       10,   11,   12,   10,   13,   11,   14,   15,   16,   10,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   28,   28,   29,   30,   31,   32,   33,   10,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   41,
       43,   44,   45,   46,   47,   41,   48,   49,   50,   51,
       41,   52,   41,   41,   53,   10,   54,   55,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   41,   48,   49,   50,   51,   41,   52,   41,
       41,   57,   57,   61,   62,   61,   62,   63,  256,   63,
       84,   65,   92,   58,   58,   71,   71,   71,   71,   72,

      219,   95,   93,   88,   73,   74,   96,   75,   75,   75,
       76,   94,   74,   89,   81,   81,   81,   81,   90,   91,
       92,   77,   69,  100,  112,  101,  142,   78,   77,   95,
       93,   88,  102,   96,   82,  104,   79,  103,   94,   80,
       89,   97,   67,   83,   98,   90,   91,   99,  113,   77,
      100,  112,  107,  101,   78,  126,   77,  128,  105,  102,
      108,   82,  127,   79,  103,  141,   80,  106,   97,  109,
       83,   98,  114,  104,   99,  113,  115,   86,  110,  148,
      107,   85,  146,  126,  111,  128,  105,  147,  108,  129,
      129,  129,  141,  155,  106,  123,   70,  109,  149,   69,

      114,   69,  124,  150,  115,  110,  139,  148,  125,  146,
       67,  111,  116,  117,  147,  140,  144,  118,  151,  152,
      155,  130,  156,  123,  119,  145,  149,  120,  121,   69,
      124,  150,  122,  139,   74,  125,   75,   75,   75,   76,
      116,  117,  140,  144,  157,  118,  151,  152,  130,  156,
       77,  119,  145,   65,  120,  121,   78,  153,  154,  122,
       71,   71,   71,   71,  158,   79,  159,   71,   71,   71,
       71,  157,   64,  289,  131,  132,   59,  160,   77,  165,
      133,  134,  135,   78,  153,  154,   59,  136,  166,  289,
      167,  158,   79,  159,  289,   74,  168,   76,   76,   76,

       76,  161,  131,  132,  160,  162,  165,  133,  163,  134,
      135,   77,  164,  137,  136,  137,  166,  167,  138,  138,
      138,  138,   74,  168,   81,   81,   81,   81,  161,  169,
      170,  171,  162,  174,  175,  176,  163,  172,   77,   77,
      164,  179,  173,  177,   82,  178,  289,  180,  181,  182,
      183,  184,  185,   83,  186,  187,  169,  170,  171,  188,
      174,  140,  175,  176,  289,  172,   77,  197,  179,  173,
      177,   82,  289,  178,  180,  181,  182,  183,  184,  185,
       83,  128,  186,  187,  289,  289,  289,  188,  140,  289,
      189,  189,  189,  191,  197,  191,  289,  199,  192,  192,

      192,  192,  193,  209,  193,  145,  203,  194,  194,  194,
      194,  138,  138,  138,  138,  138,  138,  138,  138,  200,
      204,  205,  206,  201,  207,   69,  208,  212,  202,  210,
      195,  209,  145,  203,  213,  196,  211,  289,  214,  215,
      216,  217,  289,  218,  220,  221,  200,  204,  205,  206,
      201,  207,  222,  208,  212,  202,  223,  210,  195,  224,
      232,  213,  196,  225,  211,  214,  215,  216,  226,  217,
      218,  220,  231,  221,  192,  192,  192,  192,  289,  222,
      194,  194,  194,  194,  223,  289,  289,  224,  232,  233,
      225,  234,  289,  289,  289,  226,  227,  227,  227,  231,

      228,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  235,  236,  233,  234,  229,
      229,  229,  229,  229,  229,  237,  128,  238,  239,  240,
      248,  248,  248,  248,  243,  241,  241,  241,  289,  289,
      289,  244,  235,  289,  236,  289,  249,  250,  251,  229,
      229,  229,  229,  237,  238,  239,  240,  192,  192,  192,
      192,  243,  252,  289,  194,  194,  194,  194,  244,  245,
       69,  128,  132,  249,  250,  253,  251,  133,  246,  135,
      242,  242,  242,  242,  136,  254,  255,  257,  260,  252,
      242,  242,  242,  242,  242,  242,  245,  289,  258,  263,

      132,  259,  253,  289,  133,  246,  289,  135,  289,  261,
      289,  136,  254,  255,  257,   69,  260,  289,  242,  242,
      242,  242,  242,  242,  247,  258,  247,  263,  259,  248,
      248,  248,  248,  227,  227,  227,  261,  228,  227,  227,
      227,  289,  228,  289,  289,  289,  262,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  289,  246,  289,  289,  229,  229,  229,  229,
      229,  229,  264,  262,  264,  270,  271,  265,  265,  265,
      265,  266,  272,  266,  289,  273,  267,  267,  267,  267,
      246,  248,  248,  248,  248,  274,  229,  229,  229,  229,

      275,  276,  270,  277,  271,  278,  268,  283,  284,  285,
      272,  269,  273,  265,  265,  265,  265,  267,  267,  267,
      267,  286,  274,  287,  288,  289,  289,  275,  289,  276,
      289,  277,  278,  289,  268,  283,  284,  285,  269,  265,
      265,  265,  265,  289,  289,  267,  267,  267,  267,  286,
      287,  288,  289,  289,  279,  289,  289,  289,  289,  280,
      281,  289,  289,  289,  289,  282,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  279,  289,  289,  289,  280,  289,  281,  289,
      289,  289,  282,   56,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   66,   66,   66,   66,   66,
       66,   66,   66,   68,   68,  289,   68,   68,  289,   68,
       68,   68,   68,   68,   87,   87,   87,   87,   68,   68,
      289,   68,  289,  289,   68,  143,  143,  143,  190,  190,
      198,  198,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,    9,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289
    } ;

static yyconst flex_int16_t yy_chk[955] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    7,    7,    8,    8,    7,  219,    8,
       31,   31,   35,    3,    4,   25,   25,   25,   25,   26,

      166,   37,   36,   34,   26,   27,   38,   27,   27,   27,
       27,   36,   28,   34,   28,   28,   28,   28,   34,   34,
       35,   27,  104,   40,   46,   42,   80,   27,   28,   37,
       36,   34,   42,   38,   28,   43,   27,   42,   36,   27,
       34,   39,   66,   28,   39,   34,   34,   39,   47,   27,
       40,   46,   44,   42,   27,   52,   28,   68,   43,   42,
       44,   28,   58,   27,   42,   79,   27,   43,   39,   45,
       28,   39,   48,   51,   39,   47,   48,   33,   45,   89,
       44,   32,   83,   52,   45,  241,   43,   88,   44,   69,
       69,   69,   79,   95,   43,   50,   21,   45,   90,   18,

       48,   68,   50,   91,   48,   45,   78,   89,   50,   83,
       15,   45,   49,   49,   88,   78,   82,   49,   92,   93,
       95,   69,   96,   50,   49,   82,   90,   49,   49,  241,
       50,   91,   49,   78,   75,   50,   75,   75,   75,   75,
       49,   49,   78,   82,   97,   49,   92,   93,   69,   96,
       75,   49,   82,   14,   49,   49,   75,   94,   94,   49,
       71,   71,   71,   71,   98,   75,   99,   74,   74,   74,
       74,   97,   13,    9,   71,   71,    6,  100,   75,  105,
       71,   74,   74,   75,   94,   94,    5,   74,  106,    0,
      107,   98,   75,   99,    0,   76,  108,   76,   76,   76,

       76,  102,   71,   71,  100,  102,  105,   71,  103,   74,
       74,   76,  103,   77,   74,   77,  106,  107,   77,   77,
       77,   77,   81,  108,   81,   81,   81,   81,  102,  109,
      110,  111,  102,  114,  115,  115,  103,  113,   81,   76,
      103,  117,  113,  115,   81,  116,    0,  118,  119,  120,
      121,  122,  123,   81,  124,  125,  109,  110,  111,  126,
      114,  139,  115,  115,    0,  113,   81,  141,  117,  113,
      115,   81,    0,  116,  118,  119,  120,  121,  122,  123,
       81,  129,  124,  125,  229,  229,  229,  126,  139,    0,
      129,  129,  129,  131,  141,  131,    0,  143,  131,  131,

      131,  131,  134,  153,  134,  144,  146,  134,  134,  134,
      134,  137,  137,  137,  137,  138,  138,  138,  138,  143,
      147,  149,  150,  143,  151,  129,  152,  157,  143,  154,
      138,  153,  144,  146,  159,  138,  156,    0,  160,  161,
      162,  163,    0,  164,  169,  171,  143,  147,  149,  150,
      143,  151,  172,  152,  157,  143,  173,  154,  138,  174,
      179,  159,  138,  175,  156,  160,  161,  162,  176,  163,
      164,  169,  178,  171,  191,  191,  191,  191,    0,  172,
      193,  193,  193,  193,  173,    0,    0,  174,  179,  180,
      175,  181,    0,    0,    0,  176,  177,  177,  177,  178,

      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  182,  184,  180,  181,  177,
      177,  177,  177,  177,  177,  185,  189,  186,  187,  188,
      247,  247,  247,  247,  198,  189,  189,  189,    0,    0,
        0,  199,  182,    0,  184,    0,  202,  207,  209,  177,
      177,  177,  177,  185,  186,  187,  188,  192,  192,  192,
      192,  198,  212,    0,  194,  194,  194,  194,  199,  200,
      189,  190,  192,  202,  207,  215,  209,  192,  200,  194,
      190,  190,  190,  190,  194,  217,  218,  221,  226,  212,
      190,  190,  190,  190,  190,  190,  200,    0,  222,  240,

      192,  224,  215,    0,  192,  200,    0,  194,    0,  232,
        0,  194,  217,  218,  221,  190,  226,    0,  190,  190,
      190,  190,  190,  190,  201,  222,  201,  240,  224,  201,
      201,  201,  201,  227,  227,  227,  232,  227,  228,  228,
      228,    0,  228,  230,  230,  230,  239,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,    0,  245,    0,    0,  230,  230,  230,  230,
      230,  230,  243,  239,  243,  249,  251,  243,  243,  243,
      243,  244,  254,  244,    0,  255,  244,  244,  244,  244,
      245,  248,  248,  248,  248,  257,  230,  230,  230,  230,

      259,  260,  249,  261,  251,  262,  248,  272,  274,  277,
      254,  248,  255,  264,  264,  264,  264,  266,  266,  266,
      266,  283,  257,  284,  285,    0,    0,  259,    0,  260,
        0,  261,  262,    0,  248,  272,  274,  277,  248,  265,
      265,  265,  265,    0,    0,  267,  267,  267,  267,  283,
      284,  285,    0,    0,  265,    0,    0,    0,    0,  265,
      267,    0,    0,    0,    0,  267,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  265,    0,    0,    0,  265,    0,  267,    0,
        0,    0,  267,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  292,  292,  292,  292,  292,
      292,  292,  292,  293,  293,    0,  293,  293,    0,  293,
      293,  293,  293,  293,  294,  294,  294,  294,  295,  295,
        0,  295,    0,    0,  295,  296,  296,  296,  297,  297,
      298,  298,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "epython.l"
#line 2 "epython.l"
#include "parser.h"
#include "stack.h"

static const unsigned int TAB_WIDTH = 4;

int line_num = 0, indent_caller;
int line_indent=0, fake_outdent_symbol=0;

extern struct stack_t indent_stack;

void yyget_INTEGER(YYSTYPE*, char*, size_t);
void yyget_REAL (YYSTYPE*, char*, size_t);
void yyget_STRING(YYSTYPE*, char*, size_t);

#define yyget_IDENTIFIER yyget_STRING
#define SAVE_VALUE(type)					\
{						\
        yyget_##type(&yylval, yytext, yyleng);	\
        return  type;				\
}

void yyget_INTEGER(YYSTYPE *outval, char *text, size_t len) {
	outval->integer = atoi(text);
}

void yyget_REAL(YYSTYPE *outval, char *text, size_t len) {
	outval->real = atof(text);
}

void yyget_STRING(YYSTYPE *outval, char *text, size_t len) {
	outval->string = text;
}
/* Python indentation handling based upon code at https://github.com/lucasb-eyer/flex-bison-indentation and 
http://www.benbarbour.com/implementing-python-style-indention-syntax-using-flex-bison-or-lexyacc */



#line 810 "lexer.c"

#define INITIAL 0
#define COMMENTS 1
#define SINGLELINECOMMENT 2
#define INDENT_MODE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 61 "epython.l"


#line 1003 "lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 290 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 873 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "epython.l"
{BEGIN(COMMENTS);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "epython.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 65 "epython.l"
{ ++line_num; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 66 "epython.l"
{ ++line_num;BEGIN(INITIAL); return NEWLINE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "epython.l"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "epython.l"
{ line_indent++; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 70 "epython.l"
{ line_indent+=TAB_WIDTH; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 71 "epython.l"
{ line_indent=0; }
	YY_BREAK
case YY_STATE_EOF(INDENT_MODE):
#line 72 "epython.l"
{ 	if (peek(&indent_stack) > 0) {
						pop(&indent_stack);
						if (line_indent < peek(&indent_stack)) {
							int i;
                            unput('\n');
                            for (i=0;i<peek(&indent_stack);i++) unput(' ');                            
                        } else {											
							BEGIN(indent_caller);
						}
						return OUTDENT;						
					} else {
						yyterminate();
					}					 
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "epython.l"
{
					if (!fake_outdent_symbol) unput(*yytext);					
					fake_outdent_symbol=0;
					if (line_indent > 0 && line_indent > peek(&indent_stack)) {
						push(&indent_stack, line_indent);						
						BEGIN(indent_caller);						
						return INDENT;
					} else if (line_indent < peek(&indent_stack)) {
						pop(&indent_stack);
						if (line_indent != peek(&indent_stack)) {
							int i;
							for(i=0;i<line_indent;i++) unput(' ');
                            unput('\n');                            
                            unput('.');                          
                            fake_outdent_symbol=1;
                            for(i=0;i<peek(&indent_stack);i++) unput(' ');
                            unput('\n');
						} else {
							BEGIN(indent_caller);
						}
						return OUTDENT;
					} else {
						BEGIN(indent_caller);
					}
				}									
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 112 "epython.l"
{ ++line_num; line_indent=0; indent_caller = YY_START; BEGIN(INDENT_MODE); return NEWLINE; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 113 "epython.l"
;
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 114 "epython.l"
return REM;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "epython.l"
SAVE_VALUE(STRING);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "epython.l"
SAVE_VALUE(INTEGER); 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "epython.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "epython.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "epython.l"
SAVE_VALUE(INTEGER);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "epython.l"
SAVE_VALUE(REAL); 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 123 "epython.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 124 "epython.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 125 "epython.l"
SAVE_VALUE(REAL); 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 126 "epython.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 127 "epython.l"
SAVE_VALUE(REAL);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 129 "epython.l"
return AND;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 130 "epython.l"
return OR;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 131 "epython.l"
return NOT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 132 "epython.l"
return NEQ;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 133 "epython.l"
return LEQ;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 134 "epython.l"
return GEQ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 135 "epython.l"
return LT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 136 "epython.l"
return GT;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 137 "epython.l"
return ASSGN;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 138 "epython.l"
return EQ;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 139 "epython.l"
return POW;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 140 "epython.l"
return COMMA;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 141 "epython.l"
return COLON;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 142 "epython.l"
return ADD;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 143 "epython.l"
return SUB;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 144 "epython.l"
return MULT;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 145 "epython.l"
return DIV;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 146 "epython.l"
return MOD;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 147 "epython.l"
return SLBRACE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 148 "epython.l"
return SRBRACE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 149 "epython.l"
return LPAREN;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 150 "epython.l"
return RPAREN;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 151 "epython.l"
return ISHOST;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 152 "epython.l"
return ISDEVICE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 153 "epython.l"
return ELSE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 154 "epython.l"
return SEND;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 155 "epython.l"
return RECV;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 156 "epython.l"
return SENDRECV;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 157 "epython.l"
return TOFROM;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 158 "epython.l"
return SYNC;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 159 "epython.l"
return BCAST;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 160 "epython.l"
return REDUCE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 161 "epython.l"
return INTO;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 162 "epython.l"
return SUM;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 163 "epython.l"
return MIN;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 164 "epython.l"
return MAX;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 165 "epython.l"
return PROD;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 166 "epython.l"
return DIM;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 167 "epython.l"
return SDIM;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 168 "epython.l"
return WHILE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 169 "epython.l"
return LET;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 170 "epython.l"
return STOP;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 171 "epython.l"
return FOR;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 172 "epython.l"
return TO;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 173 "epython.l"
return FROM;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 174 "epython.l"
return NEXT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 175 "epython.l"
return GOTO;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 176 "epython.l"
return IF;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 177 "epython.l"
return THEN;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 178 "epython.l"
return PRINT;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 179 "epython.l"
return INPUT;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 180 "epython.l"
return COREID;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 181 "epython.l"
return NUMCORES;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 182 "epython.l"
return RANDOM;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 183 "epython.l"
return SQRT;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 184 "epython.l"
return SIN;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 185 "epython.l"
return COS;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 186 "epython.l"
return TAN;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 187 "epython.l"
return ASIN;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 188 "epython.l"
return ACOS;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 189 "epython.l"
return ATAN;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 190 "epython.l"
return SINH;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 191 "epython.l"
return COSH;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 192 "epython.l"
return TANH;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 193 "epython.l"
return FLOOR;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 194 "epython.l"
return CEIL;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 195 "epython.l"
return LOG;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 196 "epython.l"
return LOG10;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 197 "epython.l"
BEGIN(SINGLELINECOMMENT);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 198 "epython.l"
BEGIN(SINGLELINECOMMENT);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 200 "epython.l"
return yytext[0];
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 202 "epython.l"
SAVE_VALUE(IDENTIFIER);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 203 "epython.l"
ECHO;
	YY_BREAK
#line 1613 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENTS):
case YY_STATE_EOF(SINGLELINECOMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 290 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 290 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 289);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 203 "epython.l"



