/*
 * Copyright (c) 2015, Nick Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef BASICTOKENS_H_
#define BASICTOKENS_H_

#define LET_TOKEN 0x0000
#define PRINT_TOKEN 0x0001
#define STOP_TOKEN 0x0002
#define OR_TOKEN 0x0003
#define AND_TOKEN 0x0004
#define EQ_TOKEN 0x0005
#define NEQ_TOKEN 0x0006
#define LT_TOKEN 0x0007
#define GT_TOKEN 0x0008
#define LEQ_TOKEN 0x0009
#define GEQ_TOKEN 0x000A
#define ADD_TOKEN 0x000B
#define SUB_TOKEN 0x000C
#define MUL_TOKEN 0x000D
#define DIV_TOKEN 0x000E
#define MOD_TOKEN 0x000F
#define IDENTIFIER_TOKEN 0x0010
#define REAL_TOKEN 0x0011
#define STRING_TOKEN 0x0012
#define INTEGER_TOKEN 0x0013
#define IF_TOKEN 0x0014
#define FOR_TOKEN 0x0015
#define GOTO_TOKEN 0x0016
#define INPUT_TOKEN 0x0017
#define COREID_TOKEN 0x0018
#define DIMARRAY_TOKEN 0x0019
#define ARRAYACCESS_TOKEN 0x001A
#define ARRAYSET_TOKEN 0x001B
#define SEND_TOKEN 0x001C
#define RECV_TOKEN 0x001D
#define IFELSE_TOKEN 0x001E
#define RECVTOARRAY_TOKEN 0x001F
#define POW_TOKEN 0x0020
#define MATHS_TOKEN 0x0021
#define RANDOM_TOKEN 0x0022
#define DIMSHAREDARRAY_TOKEN 0x0023
#define SYNC_TOKEN 0x0024
#define BCAST_TOKEN 0x0025
#define REDUCTION_TOKEN 0x0026
#define INPUT_STRING_TOKEN 0x0027
#define SENDRECV_TOKEN 0x0028
#define SENDRECVARRAY_TOKEN 0x0029
#define NUMCORES_TOKEN 0x002A
#define ISHOST_TOKEN 0x002B
#define ISDEVICE_TOKEN 0x002C
#define RETURN_TOKEN 0x002D
#define FNCALL_TOKEN 0x002E
#define RETURN_EXP_TOKEN 0x002F
#define BOOLEAN_TOKEN 0x0030

#define SQRT_MATHS_OP 0x0000
#define SIN_MATHS_OP 0x0001
#define COS_MATHS_OP 0x0002
#define TAN_MATHS_OP 0x0003
#define ASIN_MATHS_OP 0x0004
#define ACOS_MATHS_OP 0x0005
#define ATAN_MATHS_OP 0x0006
#define SINH_MATHS_OP 0x0007
#define COSH_MATHS_OP 0x0008
#define TANH_MATHS_OP 0x0009
#define FLOOR_MATHS_OP 0x000A
#define CEIL_MATHS_OP 0x000B
#define LOG_MATHS_OP 0x000C
#define LOG10_MATHS_OP 0x000D
#define RANDOM_MATHS_OP 0x000E

#endif /* BASICTOKENS_H_ */
