/*
 * Copyright (c) 2015, Nick Brown
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef BASICTOKENS_H_
#define BASICTOKENS_H_

#define LET_TOKEN 0x00
#define STOP_TOKEN 0x02
#define OR_TOKEN 0x03
#define AND_TOKEN 0x04
#define EQ_TOKEN 0x05
#define NEQ_TOKEN 0x06
#define LT_TOKEN 0x07
#define GT_TOKEN 0x08
#define LEQ_TOKEN 0x09
#define GEQ_TOKEN 0x0A
#define ADD_TOKEN 0x0B
#define SUB_TOKEN 0x0C
#define MUL_TOKEN 0x0D
#define DIV_TOKEN 0x0E
#define MOD_TOKEN 0x0F
#define IDENTIFIER_TOKEN 0x10
#define REAL_TOKEN 0x11
#define STRING_TOKEN 0x12
#define INTEGER_TOKEN 0x13
#define IF_TOKEN 0x14
#define FOR_TOKEN 0x15
#define GOTO_TOKEN 0x16
#define DIMARRAY_TOKEN 0x19
#define ARRAYACCESS_TOKEN 0x1A
#define ARRAYSET_TOKEN 0x1B
#define IFELSE_TOKEN 0x1E
#define POW_TOKEN 0x20
#define MATHS_TOKEN 0x21
#define DIMSHAREDARRAY_TOKEN 0x23
#define RETURN_TOKEN 0x2D
#define FNCALL_TOKEN 0x2E
#define RETURN_EXP_TOKEN 0x2F
#define BOOLEAN_TOKEN 0x30
#define LETNOALIAS_TOKEN 0x32
#define NONE_TOKEN 0x33
#define IS_TOKEN 0x34
#define ARRAY_TOKEN 0x35
#define NOT_TOKEN 0x036
#define NATIVE_TOKEN 0x3B

#define SQRT_MATHS_OP 0x00
#define SIN_MATHS_OP 0x01
#define COS_MATHS_OP 0x02
#define TAN_MATHS_OP 0x03
#define ASIN_MATHS_OP 0x04
#define ACOS_MATHS_OP 0x05
#define ATAN_MATHS_OP 0x06
#define SINH_MATHS_OP 0x07
#define COSH_MATHS_OP 0x08
#define TANH_MATHS_OP 0x09
#define FLOOR_MATHS_OP 0x0A
#define CEIL_MATHS_OP 0x0B
#define LOG_MATHS_OP 0x0C
#define LOG10_MATHS_OP 0x0D
#define RANDOM_MATHS_OP 0x0E

#define ERR_STR_ONLYTEST_EQ 0x00
#define ERR_NONE_ONLYTEST_EQ 0x01
#define ERR_ONLY_ADDITION_STR 0x02
#define ERR_TOO_MANY_ARR_INDEX 0x03
#define ERR_NEG_ARR_INDEX 0x04
#define ERR_ARR_INDEX_EXCEED_SIZE 0x05
#define ERR_ONLY_DISPLAY_STR_WITH_INPUT 0x06
#define ERR_OUT_OF_SHARED_HEAP_MEM 0x07
#define ERR_OUT_OF_CORE_SHARED_HEAP_MEM 0x08
#define ERR_OUT_OF_SHARED_STACK_MEM 0x09
#define ERR_OUT_OF_CORE_SHARED_STACK_MEM 0x0A
#define ERR_ONLY_SEND_INT_AND_REAL 0x0B
#define ERR_SEND_TO_UNKNOWN_CORE 0x0C
#define ERR_SEND_TO_INACTIVE_CORE 0x0D
#define ERR_RECV_FROM_UNKNOWN_CORE 0x0E
#define ERR_RECV_FROM_INACTIVE_CORE 0x0F
#define ERR_SENDRECV_WITH_UNKNOWN_CORE 0x10
#define ERR_FREE_ON_NON_HEAP 0x11
#define ERR_INCORRECT_NUM_NATIVE_PARAMS 0x12
#define ERR_UNKNOWN_NATIVE_COMMAND 0x13

#define NATIVE_FN_RTL_ISHOST 0x00
#define NATIVE_FN_RTL_ISDEVICE 0x01
#define NATIVE_FN_RTL_PRINT 0x02
#define NATIVE_FN_RTL_NUMDIMS 0x03
#define NATIVE_FN_RTL_DSIZE 0x04
#define NATIVE_FN_RTL_INPUT 0x05
#define NATIVE_FN_RTL_INPUTPRINT 0x06
#define NATIVE_FN_RTL_SYNC 0x07
#define NATIVE_FN_RTL_GC 0x08
#define NATIVE_FN_RTL_FREE 0x09
#define NATIVE_FN_RTL_SEND 0x0A
#define NATIVE_FN_RTL_RECV 0x0B
#define NATIVE_FN_RTL_SENDRECV 0x0C
#define NATIVE_FN_RTL_BCAST 0x0D
#define NATIVE_FN_RTL_NUMCORES 0x0E
#define NATIVE_FN_RTL_COREID 0x0F
#define NATIVE_FN_RTL_RANDOM 0x10
#define NATIVE_FN_RTL_REDUCE 0x11

#endif /* BASICTOKENS_H_ */
